__all__ = ['test_pytest_fibonacci',
           'test_fibonacci_mod',
           'test_pytest_fibonacci_mod',
           'test_pytest_ways_to_cover_in_3_steps',
           'test_min_max_afford',
           'test_pytest_min_max_afford',
           'test_longest_sequence',
           'test_pytest_paths_without_crossing.py',
           'test_friend_pairs',
           'test_optimized_painting_fence',
           'test_nose_paths_without_crossing',
           'test_ways_to_write_n_as_sum_of_integers',
           'test_pytest_ways_to_sum',
           'test_nose_yakobstelnum',
           'test_nose_palindrom',
           'test_pytest_optimized_painting_fence']
