__all__ = ['fibonacci',
           'fibonacci_mod',
           'yakobstelnum',
           'ways_to_sum',
           'ways_to_cover_in_3_steps',
           'min_max_afford',
           'longest_sequence',
           'ways_tile_floor',
           'paths_without_crossing',
           'palindrom',
           'friend_pairs',
           'optimized_painting_fence',
           'ways_to_write_n_as_sum_of_integers',
           'painting_the_fence']
